### ISSUE TITLE
Train the model

### ISSUE THREAD

**Issue by minhdl93** [IssamLaradji/CBStyling#1]
Hi,

Your project is very interesting. I like to implement it, so can you share the training code, or guide me on how to perform the training.

Thank you very much,

**Comment by IssamLaradji** [comment]
Hiya,

Thanks for your interest!

- For segmentation, we used the pretrained model in [1] 
- For style transfer, we used the pretrained model in [2].

In this work we combined these two pretrained models to segment different objects in a scene. But if you would like to train for segmenting new objects or new styles, you can use the training scripts in [1,2].

Hope this helps!

[1] https://github.com/Reagan1311/DABNet/
[2] https://github.com/pytorch/examples/tree/master/fast_neural_style

**Comment by minhdl93** [comment]
Thank you very much. Issue closed
