### ISSUE TITLE
 invalid int value: 'styles/mosaic.pth'

### ISSUE THREAD

**Issue by minhdl93** [IssamLaradji/CBStyling#2]
Hi, when I tried to run your code with the pre-trained mosaic.pth. It showed this error. 

`main.py: error: argument -s/--style: invalid int value: 'styles/mosaic.pth'`

Because your code accepts the style argument of type int parser.add_argument. Can you check it?

`("-s", "--style", type=int, default=0, help="Choose a style 0-3")`

Thank you

**Comment by IssamLaradji** [comment]
Hi @DangLienMinh , sorry about that.
Should be fixed now.

Pull the updates from this repo, and run, 
`python main.py -i images/example.png -o images/stylized.png -s 0 -c 13`

you should get a stylized image in `images/stylized.png`. Let me know how this goes :)

Cheers.
