### ISSUE TITLE
Versioning of packages

### ISSUE THREAD

**Issue by danperazzo** [IssamLaradji/CBStyling#3]
Hello, thanks for sharing your work! What were the versions of the packages that your team used for this project? (specifically, what is the version of PyTorch)

**Comment by IssamLaradji** [comment]
Thanks for your interest! We used PyTorch 1.4, did you have issues with the latest versions of the packages?

**Comment by danperazzo** [comment]
It worked all right with the latest release :))

**Comment by IssamLaradji** [comment]
perfect! :)
